name: Automatische Aktualisierung Aktiendaten

on:
  schedule:
    # Führt das Skript 3-mal am Tag aus (Zeiten sind in UTC angegeben)
    # 07:30 UTC = 09:30 Uhr dt. Zeit (Europa Open)
    # 13:30 UTC = 15:30 Uhr dt. Zeit (USA Open)
    # 20:15 UTC = 22:15 Uhr dt. Zeit (USA Close)
    - cron: '30 7 * * *'
    - cron: '30 13 * * *'
    - cron: '15 20 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh-data:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4

    - name: Python einrichten
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Abhängigkeiten installieren
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Daten abrufen und konvertieren
      run: python hole_daten.py

    - name: Änderungen in GitHub speichern
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add daten.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Daten-Update: 3x täglicher Turnus" && git push)
